name: cryptoast
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - s3fs=0.2.0
  - pylint
  - numpy
  - pandas
  - ipykernel
  - jupyter
  - plotly
  - matplotlib
  - scikit-learn
  - statsmodels
  - tsfresh
  - libuv=1.40.0
  - pytorch=1.7.0
  - torchvision=0.8.1
  - torchaudio=0.7.0
  - cudatoolkit=11.0
  - pip
  - pip:
    - python-binance==0.7.5
    - ta==0.7.0
    - stable-baselines3
