name: cryptoast-tf
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.7
  - s3fs=0.2.0
  - pylint
  - numpy
  - pandas
  - ipykernel
  - jupyter
  - plotly
  - matplotlib
  - scikit-learn
  - statsmodels
  - tsfresh
  - cudatoolkit=10.0
  # - cudnn=7.4
  - pip
  - pip:
    - python-binance==0.7.5
    - stable-baselines
    - tensorflow-gpu==1.15
